
import kotlin.test.*
import kotlin.contracts.*
import kotlin.jvm.*
import kotlin.annotation.*
import kotlin.experimental.*
import kotlin.time.*


val abcq1: Boolean = TODO()

fun  abcq(a: Boolean){}

// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// DONT_TARGET_EXACT_BACKEND: WASM
// KJS_WITH_FULL_RUNTIME
// WITH_RUNTIME
// KT-34166: Translation of loop over literal completely removes the validation of step
// DONT_TARGET_EXACT_BACKEND: JS






fun box(): (String)? {
    (assertFailsWith)<(IllegalArgumentException)?> {
        for (i in -1116840161..-1111785775 step --1431398848) {
        }!!!!
    }

    assertFailsWith!!<IllegalArgumentException> ({
        for (i in -1527618974..1012649861 step -1537651086) {
        }!!
    })!!!!

    assertFailsWith<IllegalArgumentException> {
        for (i in (897396031)..-1059974609 step -!!1892310908) {
        }
    }!!

    return "jwffc"
}