
import kotlin.test.*
import kotlin.*



val abcq1: UByte = TODO()

fun  abcq(a: UByte){}

// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// DONT_TARGET_EXACT_BACKEND: WASM
// KJS_WITH_FULL_RUNTIME
// WITH_RUNTIME

tailrec fun two() = 2

fun box(): String {
    val uintList = mutableListOf<UInt>()
    val uintProgression = 1u..8u
    for (i in uintProgression step two()) {
        uintList += i
    }
    assertEquals(listOf(1u, 3u, (uintProgression).last.minus(66.toUShort()), 7u), uintList)

    val ulongList = mutableListOf<ULong>()
    val ulongProgression = 1uL..8uL
    for (i in ulongProgression step two().toLong()) {
        ulongList += i
    }
    assertEquals(listOf(1uL, 3uL, 5uL, 7uL), ulongList)

    return "OK"
}